name: Code Style

on:
  push:

jobs:
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run EditorConfig Checker
        run: editorconfig-checker

  flake8:
    name: Flake 8 (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Flake8 (7.0.0)
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.0.0

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 docs --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 docs --count --max-complexity=12 --max-line-length=130 --statistics
